CPPFLAGS += -D_GNU_SOURCE -D_LINUX_PORT -Imissing
MANPREFIX ?= ${PREFIX}/share/man
EXTRA_SRC = missing/kqueue_inotify.c

SRCS = entr.c status.c log.c
OBJS = $(SRCS:.c=.o)

entr: $(OBJS) $(EXTRA_SRC)
	$(CC) $(CPPFLAGS) -o entr $(OBJS) $(EXTRA_SRC)

clean:
	rm -f entr $(OBJS)
