CPPFLAGS += -D_GNU_SOURCE -D_LINUX_PORT -Iproject -Imissing
MANPREFIX ?= ${PREFIX}/share/man
EXTRA_SRC = project/inotify.c project/strlcpy.c

SRCS = entr.c status.c log.c
OBJS = $(SRCS:.c=.o)

entr: $(OBJS) $(EXTRA_SRC)
	$(CC) $(CPPFLAGS) -o entr $(OBJS) $(EXTRA_SRC)

clean:
	rm -f entr $(OBJS)
