#!/bin/sh
# reload-browser, a cross-platform wrapper for reloading the current browser tab
# http://entrproject.org/

usage() {
	case `uname` in
	Darwin)
		# applescript needs the exact title
		echo "Usage: $(basename $0) Firefox [Safari \"Google Chrome\" ...]"
		;;
	*)
		# xdotool uses regular expressions
		echo "Usage: $(basename $0) Firefox [Safari Chrome ...]"
		;;
	esac
	exit 1
}
[ $# -lt 1 ] && usage

for app in "$@"
do
	case `uname` in
	Darwin)
		/usr/bin/osascript <<-APPLESCRIPT
		tell application "$app"
		  activate
		  tell application "System Events" to keystroke "r" using command down
		end tell
		APPLESCRIPT
		;;
	*)
		xdotool search --onlyvisible --class "$app" windowfocus \
		    key 'ctrl+r' || {
			1>&2 echo "unable to signal an application named \"$app\""
		}
		;;
	esac
done
