#!/bin/sh
# reload-browser, a cross-platform wrapper for reloading the current browser tab
# http://entrproject.org/

usage() {
	case `uname` in
	Darwin)
		# applescript needs the exact title
		echo "Usage: $(basename $0) Firefox [Safari \"Google Chrome\" ...]"
		;;
	*)
		# xdotool uses regular expressions
		echo "Usage: $(basename $0) Firefox [Safari Chrome ...]"
		;;
	esac
	exit 1
}
[ $# -lt 1 ] && usage

for app in "$@"
do
	case `uname` in
	Darwin)
		/usr/bin/osascript <<-APPLESCRIPT
		set prev to (path to frontmost application as text)
		tell application "$app" to activate
		tell application "System Events"
		    keystroke "r" using {command down}
		end tell
		delay 1
		activate application prev
		APPLESCRIPT
		;;
	*)
		xdotool search --onlyvisible --class "$app" windowfocus \
		    key 'ctrl+r' || {
			1>&2 echo "unable to signal an application named \"$app\""
		}
		;;
	esac
done
